### ISSUE TITLE
[BE] 문서 수정 및 일부 API 변경

### ISSUE THREAD

**Issue by thisisyoungbin** [woowacourse-teams/2021-cvi#25]
- 게시글 전체 조회 수정 - vaccinationType=ALL

- 게시글 작성 시 설정한 백신 타입은 게시글 수정 시 바꿀 수 없음

  - 요청은 보낼 수 있지만 반영되지 않음

- 회원의 닉네임은 바꿀 수 없음

  - 요청은 보낼 수 있지만 반영되지 않음

- 회원가입 POST 요청 시 URL에 ?nickname=asldk 붙는 부분 수정

- 로그인 상태에서 하는 요청 및 응답헤더 문서에서 빠짐
  -  ex) 포스트 작성 요청시 users/{userId}가 빠지고 헤더에 Authorization 추가

**Comment by YounghoonKwon** [comment]
로그인 상태에서 하는 요청 및 응답헤더 문서에서 빠짐

ex) 포스트 작성 요청시 users/{userId}가 빠지고 헤더에 Authorization 추가

완료
